print ("sinta-se a vontade") print ("calculadora")
x = int (input ("digite um número:"))
y = int (input ("digite um número:"))
opcao = str (input ("a para adição" "\n s para subtração" "\n d para divisão" "\n m para multiplicação \n escolha:"))
print (x, y)